language: python
cache: pip
os: linux
dist: focal # OS+dist should be kept in sync with Dockerfile
arch:
  - arm64
env:
  global: # MongoDB version should be kept in sync with docker-compose image
    - MONGODB=5.0.2
jobs:
  include:

    - python: 3.8
      env: TOX_ENV=py38-pymongo361-pyexecjs


script:
  - tox -e $TOX_ENV
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "sudo apt-get update"
before_script:
  - mkdir ${PWD}/mongodb-linux-aarch64-ubuntu2004-5.0.2/data
  - ${PWD}/mongodb-linux-aarch64-ubuntu2004-5.0.2/bin/mongod --dbpath ${PWD}/mongodb-linux-aarch64-ubuntu2004-5.0.2/data --logpath ${PWD}/mongodb-linux-aarch64-ubuntu2004-5.0.2/mongodb.log --fork
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
after_script:
  - pkill mongod
install:
  - wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
  - sudo apt-get install gnupg
  - wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=5.0.2 mongodb-org-database=5.0.2 mongodb-org-server=5.0.2 mongodb-org-shell=5.0.2 mongodb-org-mongos=5.0.2 mongodb-org-tools=5.0.2
  - echo ${PWD}/mongodb-linux-aarch64-ubuntu2004-${MONGODB}/bin/mongod
  - pip install pymongo
  - whereis mongod
  - ls
  - pwd
  - cd /usr/bin/mongod
  - ls
  - pwd
  - ps --no-headers -o comm 1
  - sudo service mongod start
  - sudo service mongod status
  - mkdir -p ${PWD}/mongodb-linux-aarch64-ubuntu2004-5.0.2/bin/mongod
  - cp /usr/bin/mongod ${PWD}/mongodb-linux-aarch64-ubuntu2004-5.0.2/bin/mongod
  - pip install tox

