language: python
cache: pip
os: linux
dist: xenial # OS+dist should be kept in sync with Dockerfile

env:
  global: # MongoDB version should be kept in sync with docker-compose image
    - MONGODB=4.4.0
jobs:
  include:

    - python: 3.8
      env: TOX_ENV=py38-pymongo361-pyexecjs


script:
  - tox -e $TOX_ENV
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "sudo apt-get update"
before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/mongodb.log --fork
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - echo $prev_name
  - echo $name
  - print $prev_name
after_script:
  - pkill mongod
install:
  - wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-ubuntu1604-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/bin/mongod --version
  - pip install tox

