language: python
cache: pip
os: linux
dist: Bionic # OS+dist should be kept in sync with Dockerfile
arch:
  - arm64
env:
  global: # MongoDB version should be kept in sync with docker-compose image
    - MONGODB=4.2.0
jobs:
  include:

    - python: 3.8
      env: TOX_ENV=py38
    - python: 3.8
      env: TOX_ENV=py38-pyexecjs
    - python: 3.8
      env: TOX_ENV=py38-pymongo361-pyexecjs


script:
  - tox -e $TOX_ENV
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "sudo apt-get update"
before_script:
  - mkdir ${PWD}/mongodb-linux-aarch64-ubuntu1804-${MONGODB}/data
  - ${PWD}/mongodb-linux-aarch64-ubuntu1604-${MONGODB}/bin/mongodb --dbpath ${PWD}/mongodb-linux-aarch64-ubuntu1804-${MONGODB}/data --logpath ${PWD}/mongodb-linux-aarch64-ubuntu1804-${MONGODB}/mongodb.log --fork
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
after_script:
  - pkill mongod
install:
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -
  - apt-get install gnupg
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  - apt-get update
  - apt-get install -y mongodb-org
  - ps --no-headers -o comm 1
  - service mongod start
  - service mongod status

  - ${PWD}/mongodb-linux-aarch64-ubuntu1804-${MONGODB}/bin/mongodb --version
  - pip install tox
deploy:
  provider: pypi
  username: vmalloc
  distributions: "bdist_wheel sdist"
  password:
    secure: sNOkUNFfWKGsRy4BI+1jyqycZGSMiXTLtpCrX1mTuvjddbndULrHL3ecIPsCno49/nPR4Gww+e9U3HXc8LKJ9qR4mJ8bVCNiHO5GlGVnpV+wdGh9LVnsU1LWwuD8uWlLyTSOKP+ZmerCw7tGACYiv0e9zp8SqZXCH6VS+sAGFxU=
  on:
    tags: true
    all_branches: true
    repo: mongomock/mongomock
