language: python
cache: pip
os: linux
dist: focal # OS+dist should be kept in sync with Dockerfile
arch:
  - arm64
env:
  global: # MongoDB version should be kept in sync with docker-compose image
    - MONGODB=5.0.2
jobs:
  include:

    - python: 3.8
      env: TOX_ENV=py38-pymongo361-pyexecjs


script:
  - tox -e $TOX_ENV
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "sudo apt-get update"
before_script:
  - mkdir ${PWD}/mongodb-linux-aarch64-ubuntu2004-5.0.2/data
  - ${PWD}/mongodb-linux-aarch64-ubuntu2004-5.0.2/bin/mongod --dbpath ${PWD}/mongodb-linux-aarch64-ubuntu2004-5.0.2/data --logpath ${PWD}/mongodb-linux-aarch64-ubuntu2004-5.0.2/mongodb.log --fork
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - echo $prev_name
  - echo $name
after_script:
  - pkill mongod
install:
  - wget https://fastdl.mongodb.org/linux/mongodb-linux-aarch64-ubuntu2004-5.0.2.tgz
  - tar xzf mongodb-linux-aarch64-ubuntu2004-5.0.2.tgz
  - ${PWD}/mongodb-linux-aarch64-ubuntu2004-5.0.2/bin/mongod --version
  - pip install tox

